name: Test Upload Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dummy file
        run: echo "test" > test.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: test-artifact
          path: test.txt
